[2024-12-04T19:46:37.729+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator_test.hello scheduled__2022-12-06T00:00:00+00:00 [queued]>
[2024-12-04T19:46:37.738+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator_test.hello scheduled__2022-12-06T00:00:00+00:00 [queued]>
[2024-12-04T19:46:37.738+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-04T19:46:37.738+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-04T19:46:37.738+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-04T19:46:37.752+0000] {taskinstance.py:1383} INFO - Executing <Task(joeloperator): hello> on 2022-12-06 00:00:00+00:00
[2024-12-04T19:46:37.759+0000] {standard_task_runner.py:55} INFO - Started process 1295 to run task
[2024-12-04T19:46:37.765+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customoperator_test', 'hello', 'scheduled__2022-12-06T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/custom_operator_dag.py', '--cfg-path', '/tmp/tmph9qsvghd']
[2024-12-04T19:46:37.766+0000] {standard_task_runner.py:83} INFO - Job 47: Subtask hello
[2024-12-04T19:46:37.832+0000] {task_command.py:376} INFO - Running <TaskInstance: customoperator_test.hello scheduled__2022-12-06T00:00:00+00:00 [running]> on host 308becaf7165
[2024-12-04T19:46:37.897+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customoperator_test
AIRFLOW_CTX_TASK_ID=hello
AIRFLOW_CTX_EXECUTION_DATE=2022-12-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-06T00:00:00+00:00
[2024-12-04T19:46:37.898+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1127, in execute
    raise NotImplementedError()
NotImplementedError
[2024-12-04T19:46:37.910+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=customoperator_test, task_id=hello, execution_date=20221206T000000, start_date=20241204T194637, end_date=20241204T194637
[2024-12-04T19:46:37.924+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 47 for task hello (; 1295)
[2024-12-04T19:46:37.973+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-04T19:46:38.009+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
